// GENERATED by scripts/gen-theme.mjs from design/sankalp/design-tokens.json (od-design-tokens/v1).
// Real Sankalp values (ADR-0010/0011). color-mix() pre-resolved to static hex for RN-native.
// Do NOT hand-tune — edit design/sankalp/design-tokens.json and run `npm run gen:theme`.

export const lightTheme = {
  "fonts": {
    "display": "Marcellus-Regular",
    "body": "Mukta-Regular",
    "medium": "Mukta-Medium",
    "semibold": "Mukta-SemiBold",
    "bold": "Mukta-Bold",
    "mono": "JetBrainsMono-Regular"
  },
  "colors": {
    "bg": "#f7f1e6",
    "accent": "#b8531a",
    "brand": "#b8893f",
    "status": {
      "present": "#2f6a3a",
      "absent": "#b3402e",
      "excused": "#8a6320",
      "info": "#2c4a7a"
    },
    "role": {
      "student": "#3f6db0",
      "parent": "#4a8a5c",
      "teacher": "#7a5ba8",
      "coordinator": "#c08a3e",
      "admin": "#5a5566"
    },
    "surface": "#fffaf0",
    "surfaceAlt": "#f1e8d4",
    "bgCream": "#fbf6eb",
    "ink": "#1c1410",
    "ink2": "#3d2e22",
    "ink3": "#6b574a",
    "ink4": "#9c8773",
    "line": "#e6d8bf",
    "line2": "#d6c4a3",
    "primary": "#b8531a",
    "primaryPressed": "#8e3d10",
    "primarySoft": "#f3d9b8",
    "indigo": "#2d2056",
    "indigo2": "#1a1238",
    "gold": "#b8893f",
    "gold2": "#8a6320",
    "goldLight": "#f6c98a",
    "onAction": "#fbf3df",
    "onDark": "#fbf3df",
    "statusRamp": {
      "present": "#2f6a3a",
      "presentSoft": "#e7f1e8",
      "presentLine": "#c4dec9",
      "excused": "#8a6320",
      "excusedSoft": "#fff4e0",
      "excusedLine": "#f1d59a",
      "info": "#2c4a7a",
      "infoSoft": "#f0f4fc",
      "infoLine": "#d6e0f4",
      "absent": "#b3402e",
      "absentSoft": "#f7e3df",
      "absentLine": "#e6c3bb"
    },
    "roles": {
      "student": "#3f6db0",
      "parent": "#4a8a5c",
      "teacher": "#7a5ba8",
      "coordinator": "#c08a3e",
      "bv": "#a4508a",
      "admin": "#5a5566"
    },
    "canvas": "#f4eee1",
    "appSurface": "#fffdf8",
    "appSurface2": "#f7f0e2",
    "overlay": "rgba(28,20,16,0.46)",
    "scope": {
      "org": "#2c4a7a",
      "center": "#8a6320",
      "class": "#7a5ba8"
    },
    "chatOut": "#b8531a",
    "chatOutInk": "#fff6ea",
    "chatIn": "#fffdf8",
    "chatInInk": "#1c1410",
    "chatInLine": "#e6d8bf",
    "chatUnread": "#b8531a",
    "private": "#6d4bb0",
    "privateSoft": "#efeafa",
    "privateLine": "#ddd2f3"
  },
  "space": {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "8": 32,
    "10": 40,
    "12": 48,
    "16": 64,
    "xs": 4,
    "sm": 8,
    "md": 16,
    "lg": 24,
    "xl": 32
  },
  "radius": {
    "sm": 6,
    "md": 10,
    "lg": 18,
    "control": 10,
    "card": 14,
    "bubble": 18,
    "pill": 999
  },
  "type": {
    "body": 16,
    "display": 28,
    "scale": {
      "display": 80,
      "h1": 56,
      "h2": 36,
      "h3": 22,
      "lead": 18,
      "body": 16,
      "sm": 14,
      "xs": 13,
      "eyebrow": 11
    },
    "leading": {
      "tight": 1.05,
      "snug": 1.3,
      "body": 1.6
    },
    "tracking": {
      "display": 0.005,
      "eyebrow": 0.18,
      "mono": 0.04
    }
  },
  "motion": {
    "fast": 150,
    "base": 250,
    "ease": "cubic-bezier(0.2,0.7,0.2,1)"
  },
  "chrome": {
    "header": 56,
    "tabbar": 64,
    "gutter": 16,
    "maxw": 440,
    "deskw": 1180,
    "hitMin": 44
  }
} as const;

export const breakpoints = {
  "xs": 0,
  "sm": 360,
  "md": 768,
  "lg": 1024,
  "xl": 1440
} as const;
export type AppTheme = typeof lightTheme;
