// scripts/_adr-index.mjs
// Pure helpers for the ADR-index generator/gate (scripts/gen-adr-index.mjs) — no fs, no
// process, so every rule below is unit-testable in isolation (scripts/__tests__/adr-index.test.ts),
// matching the _secret-checks.js / _tracker-checks.js pattern. See ADR-2026-08-21-adr-identifier-scheme.
//
// The ADR files are the single source of truth. Each ADR's id (H1), title (H1), Status,
// Category, and Date are read from its header; the index is grouped by Category and written
// between the ADR-INDEX markers. The gate is fail-CLOSED: any unparseable/invalid ADR, a
// duplicate id, an unknown category, or missing markers fails the build with a NAMED error —
// it never silently degrades to a placeholder or a green check on bad content.

// Display order + emoji for the six category groups. A category outside this set is an ERROR
// (not a silent "Other" group) — the taxonomy is closed (ADR-2026-08-21-adr-identifier-scheme).
export const CATEGORIES = [
  ['UX', '🎨 Usability & Design (UX)'],
  ['Auth/Access', '🔐 Auth & Access Control'],
  ['Data', '🗄️ Data Model & DB Logic'],
  ['Privacy/Minors', '🛡️ Privacy & Minors’ Data'],
  ['Chat/Notifications', '💬 Chat & Notifications'],
  ['Infra/Process', '⚙️ Infrastructure, Delivery & Process'],
];
const CATEGORY_KEYS = new Set(CATEGORIES.map(([key]) => key));

export const START = '<!-- ADR-INDEX:START (generated by scripts/gen-adr-index.mjs — do not edit by hand) -->';
export const END = '<!-- ADR-INDEX:END -->';

// The legacy numbered set is FROZEN at ADR-0001..ADR-0038 (ADR-2026-08-21-adr-identifier-scheme:
// "existing ADRs keep their numbers"). The cutover line is 0038 — the high-water mark across
// main (0001–0033) plus the numbered ADRs already in flight when enforcement landed (0034–0036,
// 0038 on #50; 0037 on #58), grandfathered so those PRs merge as-is. No NEW numbered id may be
// minted beyond this set — new ADRs must be date-based (ADR-YYYY-MM-DD-<slug>). This is what
// makes a fresh `0039-*.md` fail the gate.
export const LEGACY_IDS = new Set(
  Array.from({ length: 38 }, (_, i) => `ADR-${String(i + 1).padStart(4, '0')}`)
);

// A real calendar date in YYYY-MM-DD form (no Date() — kept pure/deterministic).
const isValidYmd = (s) => {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(s);
  if (!m) return false;
  const [, , mm, dd] = m.map(Number);
  return mm >= 1 && mm <= 12 && dd >= 1 && dd <= 31;
};

// Extract a `**Name:** value` header field. Returns '' when absent (validation flags the miss).
export const field = (text, name) => {
  const m = text.match(new RegExp(`\\*\\*${name}:\\*\\*\\s*(.+?)\\s*(?:·\\s*\\*\\*|$)`, 'm'));
  return m ? m[1].trim() : '';
};

// The id a filename is REQUIRED to declare, plus its kind — or an error explaining why the
// filename isn't a valid ADR name at all. Legacy: NNNN-<slug>.md → ADR-NNNN (number only).
// Dated:  YYYY-MM-DD-<slug>.md → ADR-<full-stem>.
export function expectedIdForFilename(filename) {
  const stem = filename.replace(/\.md$/, '');
  if (/^\d{4}-\d{2}-\d{2}-[a-z0-9]+(?:-[a-z0-9]+)*$/.test(stem)) {
    const date = stem.slice(0, 10);
    if (!isValidYmd(date)) return { error: `filename has an invalid date "${date}" (expected YYYY-MM-DD-<slug>)` };
    return { expectedId: `ADR-${stem}`, kind: 'dated' };
  }
  const legacy = /^(\d{4})-.+$/.exec(stem);
  if (legacy) {
    const id = `ADR-${legacy[1]}`;
    if (!LEGACY_IDS.has(id)) {
      return { error: `"${id}" is not a known legacy id — new ADRs must use a date-based id (ADR-YYYY-MM-DD-<slug>), not a new number` };
    }
    return { expectedId: id, kind: 'legacy' };
  }
  return { error: `filename "${filename}" is not a valid ADR name (expected NNNN-<slug>.md for legacy or YYYY-MM-DD-<slug>.md for new)` };
}

// Parse one ADR file's raw header fields. No fallbacks/placeholders — missing values stay
// empty/null so validateAdr can flag them loudly rather than papering over them.
export function parseAdr(filename, text) {
  const h1 = text.match(/^#\s+(ADR-\S+):\s*(.+?)\s*$/m);
  return {
    file: filename,
    id: h1 ? h1[1] : null,
    title: h1 ? h1[2].trim() : '',
    status: field(text, 'Status'),
    category: field(text, 'Category'),
    date: field(text, 'Date'),
  };
}

// All problems with a single ADR, each prefixed with the filename so the failure is actionable.
export function validateAdr(adr) {
  const errors = [];
  const p = (msg) => errors.push(`${adr.file}: ${msg}`);
  const expected = expectedIdForFilename(adr.file);

  if (expected.error) {
    p(expected.error);
  } else if (!adr.id) {
    p(`missing "# ADR-…:" heading (expected id ${expected.expectedId})`);
  } else if (adr.id !== expected.expectedId) {
    p(`H1 id "${adr.id}" doesn't match the filename (expected "${expected.expectedId}")`);
  }

  if (!adr.title) p('missing title (the text after "# ADR-…:")');
  if (!adr.status) p('missing **Status:** field');
  if (!adr.category) p('missing **Category:** field');
  else if (!CATEGORY_KEYS.has(adr.category)) {
    p(`unknown **Category:** "${adr.category}" (must be one of: ${[...CATEGORY_KEYS].join(', ')})`);
  }
  if (!adr.date) p('missing **Date:** field');
  else if (!isValidYmd(adr.date)) p(`invalid **Date:** "${adr.date}" (expected YYYY-MM-DD)`);

  return errors;
}

// Two ADR files declaring the same id — the exact collision this scheme exists to prevent.
export function findDuplicateIds(adrs) {
  const byId = new Map();
  for (const a of adrs) {
    if (!a.id) continue; // a missing id is already reported by validateAdr
    if (!byId.has(a.id)) byId.set(a.id, []);
    byId.get(a.id).push(a.file);
  }
  const errors = [];
  for (const [id, files] of byId) {
    if (files.length > 1) errors.push(`duplicate id "${id}" declared by: ${files.sort().join(', ')}`);
  }
  return errors;
}

// Every problem across the whole ADR set (per-file + cross-file duplicates), sorted for
// deterministic output. Empty array ⇒ the set is valid and safe to render.
export function validateAll(adrs) {
  const errors = [...adrs.flatMap(validateAdr), ...findDuplicateIds(adrs)];
  return errors.sort(byCodepoint);
}

// Deterministic, locale-INDEPENDENT ordering (byte/codepoint), so the generated block is
// byte-identical on every machine — CI compares it exactly, and localeCompare would drift.
const byCodepoint = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

const esc = (s) => s.replace(/\|/g, '\\|');

// The generated index block (between, but not including, the markers is assembled by
// renderReadme). Assumes `adrs` already passed validateAll. Groups by CATEGORIES order;
// within a group, sorts by date then id via codepoint order.
export function buildIndexBlock(adrs) {
  const byCat = new Map();
  for (const a of adrs) {
    if (!byCat.has(a.category)) byCat.set(a.category, []);
    byCat.get(a.category).push(a);
  }
  for (const list of byCat.values()) list.sort((a, b) => byCodepoint(a.date + a.id, b.date + b.id));

  let out = `_Generated from the ADR files by \`npm run gen:adr-index\` — do not edit this block by hand (edit the ADRs). ${adrs.length} decisions._\n`;
  for (const [key, heading] of CATEGORIES) {
    const list = byCat.get(key) || [];
    if (!list.length) continue;
    out += `\n### ${heading}\n\n| ID | Decision | Status | Date |\n|---|---|---|---|\n`;
    for (const a of list) out += `| [${a.id}](${a.file}) | ${esc(a.title)} | ${esc(a.status)} | ${a.date} |\n`;
  }
  return `${START}\n\n${out.trimEnd()}\n\n${END}`;
}

// Splice a freshly-built block into the README between the markers. Fail-CLOSED: if either
// marker is missing we return an error rather than silently leaving the README untouched
// (the old fallback could make --check compare the file against itself and pass on garbage).
export function renderReadme(readmeText, block) {
  if (!readmeText.includes(START) || !readmeText.includes(END)) {
    return { error: 'README.md is missing the ADR-INDEX markers (<!-- ADR-INDEX:START … --> / <!-- ADR-INDEX:END -->) — cannot place the generated index' };
  }
  const rx = new RegExp(
    `${START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`
  );
  return { readme: readmeText.replace(rx, block) };
}
